version: '2.2'

services:
    testing-CICD:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '730:729'
        networks:
            - app-tier
        env_file:
            - .env
networks:
    app-tier:
        external: true
