name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t testingcicd:${{ github.sha }} .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Create Tag Image
      run: docker tag testingcicd:${{ github.sha }} widyafebriandaru/testingcicd:${{ github.sha }}

    - name: Push Docker image
      run: docker push widyafebriandaru/testingcicd:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull widyafebriandaru/testingcicd:${{ github.sha }}
          docker stop testingcicd || true
          docker rm testingcicd || true
          docker run -d --name testingcicd -p 730:729 widyafebriandaru/testingcicd:${{ github.sha }}
